language: ruby
bundler_args: --without production --binstubs
cache: bundler

services:
  - postgresql

before_script:
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG && cd $TRAVIS_REPO_SLUG && git checkout -qf $TRAVIS_BRANCH; fi
  - if [ $TRAVIS_PULL_REQUEST == "true" ]; then git checkout -qf master && git checkout -qf $TRAVIS_COMMIT; fi
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

notifications:
  email: false

script:
  - bundle exec rake check_style
  - xvfb-run -a bundle exec rake


after_script:
  - bundle exec codeclimate-test-reporter
